# azure-pipelines.yml

trigger:
  - master  

pool: 
  - portfolio_self_hosted_agent 


steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'



